/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ActivationRequestBuilderNavigationMetadata, type ActivationRequestBuilder } from './activation/index.js';
// @ts-ignore
import { type WithContextItemRequestBuilder, WithContextItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/extensibility/tenants/{tenantId}/extensions/{extensionId}/{contextType}
 */
export interface WithContextTypeItemRequestBuilder extends BaseRequestBuilder<WithContextTypeItemRequestBuilder> {
    /**
     * The activation property
     */
    get activation(): ActivationRequestBuilder;
    /**
     * Gets an item from the ApiSdk.api.extensibility.tenants.item.extensions.item.item.item collection
     * @param contextId Unique identifier of the item
     * @returns {WithContextItemRequestBuilder}
     */
     byContextId(contextId: string) : WithContextItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithContextTypeItemRequestBuilderUriTemplate = "{+baseurl}/api/extensibility/tenants/{tenantId}/extensions/{extensionId}/{contextType}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithContextTypeItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithContextTypeItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byContextId: {
        navigationMetadata: WithContextItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["contextId"],
    },
    activation: {
        navigationMetadata: ActivationRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
