version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    groups:
      changesets:
        patterns:
        - "@changesets*"
        - "changesets"
        update-types:
        - "major"
        - "minor"
        - "patch"
      eslint:
        patterns:
        - "eslint*"
        - "eslint"
        - "*/eslint*"
        update-types:
        - "minor"
        - "patch"
