/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ResourcesRequestBuilderNavigationMetadata, type ResourcesRequestBuilder } from './resources/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/marketplace/tenants/{tenantId}
 */
export interface WithTenantItemRequestBuilder extends BaseRequestBuilder<WithTenantItemRequestBuilder> {
    /**
     * The resources property
     */
    get resources(): ResourcesRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithTenantItemRequestBuilderUriTemplate = "{+baseurl}/api/marketplace/tenants/{tenantId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithTenantItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithTenantItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    resources: {
        navigationMetadata: ResourcesRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
