/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface Bulk400Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The error property
     */
    errorEscaped?: string | null;
    /**
     * The message property
     */
    messageEscaped?: string | null;
    /**
     * The statusCode property
     */
    statusCode?: number | null;
}
export interface Bulk404Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The error property
     */
    errorEscaped?: string | null;
    /**
     * The message property
     */
    messageEscaped?: string | null;
    /**
     * The statusCode property
     */
    statusCode?: number | null;
}
export interface Bulk500Error extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The error property
     */
    errorEscaped?: string | null;
    /**
     * The message property
     */
    messageEscaped?: string | null;
    /**
     * The statusCode property
     */
    statusCode?: number | null;
}
export interface BulkPostRequestBody extends Parsable {
    /**
     * The contextIds property
     */
    contextIds?: string[] | null;
    /**
     * The contextType property
     */
    contextType?: BulkPostRequestBody_contextType | null;
    /**
     * The overrides property
     */
    overrides?: BulkPostRequestBody_overrides[] | null;
}
export type BulkPostRequestBody_contextType = (typeof BulkPostRequestBody_contextTypeObject)[keyof typeof BulkPostRequestBody_contextTypeObject];
export interface BulkPostRequestBody_overrides extends Parsable {
    /**
     * The icon property
     */
    icon?: BulkPostRequestBody_overrides_icon | null;
    /**
     * The labelIntl property
     */
    labelIntl?: BulkPostRequestBody_overrides_labelIntl | null;
    /**
     * The order property
     */
    order?: number | null;
    /**
     * The routeId property
     */
    routeId?: string | null;
}
export interface BulkPostRequestBody_overrides_icon extends Parsable {
    /**
     * The name property
     */
    name?: string | null;
}
export interface BulkPostRequestBody_overrides_labelIntl extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
}
export interface BulkPostResponse extends Parsable {
    /**
     * The activationIds property
     */
    activationIds?: string[] | null;
}
/**
 * Builds and executes requests for operations under /api/extensibility/tenants/{tenantId}/extensions/{extensionId}/activation/bulk
 */
export interface BulkRequestBuilder extends BaseRequestBuilder<BulkRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<BulkPostResponse>}
     * @throws {Bulk400Error} error when the service returns a 400 status code
     * @throws {Bulk404Error} error when the service returns a 404 status code
     * @throws {Bulk500Error} error when the service returns a 500 status code
     */
     post(body: BulkPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<BulkPostResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: BulkPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Bulk400Error}
 */
// @ts-ignore
export function createBulk400ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoBulk400Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Bulk404Error}
 */
// @ts-ignore
export function createBulk404ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoBulk404Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Bulk500Error}
 */
// @ts-ignore
export function createBulk500ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoBulk500Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {BulkPostRequestBody_overrides_icon}
 */
// @ts-ignore
export function createBulkPostRequestBody_overrides_iconFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoBulkPostRequestBody_overrides_icon;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {BulkPostRequestBody_overrides_labelIntl}
 */
// @ts-ignore
export function createBulkPostRequestBody_overrides_labelIntlFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoBulkPostRequestBody_overrides_labelIntl;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {BulkPostRequestBody_overrides}
 */
// @ts-ignore
export function createBulkPostRequestBody_overridesFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoBulkPostRequestBody_overrides;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {BulkPostRequestBody}
 */
// @ts-ignore
export function createBulkPostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoBulkPostRequestBody;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {BulkPostResponse}
 */
// @ts-ignore
export function createBulkPostResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoBulkPostResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoBulk400Error(bulk400Error: Partial<Bulk400Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "error": n => { bulk400Error.errorEscaped = n.getStringValue(); },
        "message": n => { bulk400Error.messageEscaped = n.getStringValue(); },
        "statusCode": n => { bulk400Error.statusCode = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoBulk404Error(bulk404Error: Partial<Bulk404Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "error": n => { bulk404Error.errorEscaped = n.getStringValue(); },
        "message": n => { bulk404Error.messageEscaped = n.getStringValue(); },
        "statusCode": n => { bulk404Error.statusCode = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoBulk500Error(bulk500Error: Partial<Bulk500Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "error": n => { bulk500Error.errorEscaped = n.getStringValue(); },
        "message": n => { bulk500Error.messageEscaped = n.getStringValue(); },
        "statusCode": n => { bulk500Error.statusCode = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoBulkPostRequestBody(bulkPostRequestBody: Partial<BulkPostRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "contextIds": n => { bulkPostRequestBody.contextIds = n.getCollectionOfPrimitiveValues<string>(); },
        "contextType": n => { bulkPostRequestBody.contextType = n.getEnumValue<BulkPostRequestBody_contextType>(BulkPostRequestBody_contextTypeObject); },
        "overrides": n => { bulkPostRequestBody.overrides = n.getCollectionOfObjectValues<BulkPostRequestBody_overrides>(createBulkPostRequestBody_overridesFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoBulkPostRequestBody_overrides(bulkPostRequestBody_overrides: Partial<BulkPostRequestBody_overrides> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "icon": n => { bulkPostRequestBody_overrides.icon = n.getObjectValue<BulkPostRequestBody_overrides_icon>(createBulkPostRequestBody_overrides_iconFromDiscriminatorValue); },
        "labelIntl": n => { bulkPostRequestBody_overrides.labelIntl = n.getObjectValue<BulkPostRequestBody_overrides_labelIntl>(createBulkPostRequestBody_overrides_labelIntlFromDiscriminatorValue); },
        "order": n => { bulkPostRequestBody_overrides.order = n.getNumberValue(); },
        "routeId": n => { bulkPostRequestBody_overrides.routeId = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoBulkPostRequestBody_overrides_icon(bulkPostRequestBody_overrides_icon: Partial<BulkPostRequestBody_overrides_icon> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "name": n => { bulkPostRequestBody_overrides_icon.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoBulkPostRequestBody_overrides_labelIntl(bulkPostRequestBody_overrides_labelIntl: Partial<BulkPostRequestBody_overrides_labelIntl> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoBulkPostResponse(bulkPostResponse: Partial<BulkPostResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "activationIds": n => { bulkPostResponse.activationIds = n.getCollectionOfPrimitiveValues<string>(); },
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeBulk400Error(writer: SerializationWriter, bulk400Error: Partial<Bulk400Error> | undefined | null = {}) : void {
    if (bulk400Error) {
        writer.writeStringValue("error", bulk400Error.errorEscaped);
        writer.writeStringValue("message", bulk400Error.messageEscaped);
        writer.writeNumberValue("statusCode", bulk400Error.statusCode);
        writer.writeAdditionalData(bulk400Error.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeBulk404Error(writer: SerializationWriter, bulk404Error: Partial<Bulk404Error> | undefined | null = {}) : void {
    if (bulk404Error) {
        writer.writeStringValue("error", bulk404Error.errorEscaped);
        writer.writeStringValue("message", bulk404Error.messageEscaped);
        writer.writeNumberValue("statusCode", bulk404Error.statusCode);
        writer.writeAdditionalData(bulk404Error.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeBulk500Error(writer: SerializationWriter, bulk500Error: Partial<Bulk500Error> | undefined | null = {}) : void {
    if (bulk500Error) {
        writer.writeStringValue("error", bulk500Error.errorEscaped);
        writer.writeStringValue("message", bulk500Error.messageEscaped);
        writer.writeNumberValue("statusCode", bulk500Error.statusCode);
        writer.writeAdditionalData(bulk500Error.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeBulkPostRequestBody(writer: SerializationWriter, bulkPostRequestBody: Partial<BulkPostRequestBody> | undefined | null = {}) : void {
    if (bulkPostRequestBody) {
        writer.writeCollectionOfPrimitiveValues<string>("contextIds", bulkPostRequestBody.contextIds);
        writer.writeEnumValue<BulkPostRequestBody_contextType>("contextType", bulkPostRequestBody.contextType);
        writer.writeCollectionOfObjectValues<BulkPostRequestBody_overrides>("overrides", bulkPostRequestBody.overrides, serializeBulkPostRequestBody_overrides);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeBulkPostRequestBody_overrides(writer: SerializationWriter, bulkPostRequestBody_overrides: Partial<BulkPostRequestBody_overrides> | undefined | null = {}) : void {
    if (bulkPostRequestBody_overrides) {
        writer.writeObjectValue<BulkPostRequestBody_overrides_icon>("icon", bulkPostRequestBody_overrides.icon, serializeBulkPostRequestBody_overrides_icon);
        writer.writeObjectValue<BulkPostRequestBody_overrides_labelIntl>("labelIntl", bulkPostRequestBody_overrides.labelIntl, serializeBulkPostRequestBody_overrides_labelIntl);
        writer.writeNumberValue("order", bulkPostRequestBody_overrides.order);
        writer.writeStringValue("routeId", bulkPostRequestBody_overrides.routeId);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeBulkPostRequestBody_overrides_icon(writer: SerializationWriter, bulkPostRequestBody_overrides_icon: Partial<BulkPostRequestBody_overrides_icon> | undefined | null = {}) : void {
    if (bulkPostRequestBody_overrides_icon) {
        writer.writeStringValue("name", bulkPostRequestBody_overrides_icon.name);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeBulkPostRequestBody_overrides_labelIntl(writer: SerializationWriter, bulkPostRequestBody_overrides_labelIntl: Partial<BulkPostRequestBody_overrides_labelIntl> | undefined | null = {}) : void {
    if (bulkPostRequestBody_overrides_labelIntl) {
        writer.writeAdditionalData(bulkPostRequestBody_overrides_labelIntl.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeBulkPostResponse(writer: SerializationWriter, bulkPostResponse: Partial<BulkPostResponse> | undefined | null = {}) : void {
    if (bulkPostResponse) {
        writer.writeCollectionOfPrimitiveValues<string>("activationIds", bulkPostResponse.activationIds);
    }
}
/**
 * Uri template for the request builder.
 */
export const BulkRequestBuilderUriTemplate = "{+baseurl}/api/extensibility/tenants/{tenantId}/extensions/{extensionId}/activation/bulk";
export const BulkPostRequestBody_contextTypeObject = {
    Project: "project",
} as const;
/**
 * Metadata for all the requests in the request builder.
 */
export const BulkRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: BulkRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createBulk400ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createBulk404ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createBulk500ErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createBulkPostResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeBulkPostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
