/* eslint-disable @typescript-eslint/ban-tslint-comment */
/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ExtensionsRequestBuilderRequestsMetadata, type ExtensionsRequestBuilder } from './extensions/';
// @ts-ignore
import { TenantsRequestBuilderNavigationMetadata, type TenantsRequestBuilder } from './tenants/';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/extensibility
 */
export interface ExtensibilityRequestBuilder extends BaseRequestBuilder<ExtensibilityRequestBuilder> {
    /**
     * The extensions property
     */
    get extensions(): ExtensionsRequestBuilder;
    /**
     * The tenants property
     */
    get tenants(): TenantsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ExtensibilityRequestBuilderUriTemplate = "{+baseurl}/api/extensibility";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ExtensibilityRequestBuilderNavigationMetadata: Record<Exclude<keyof ExtensibilityRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    extensions: {
        requestsMetadata: ExtensionsRequestBuilderRequestsMetadata,
    },
    tenants: {
        navigationMetadata: TenantsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
