/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ActivationRequestBuilderRequestsMetadata, type ActivationRequestBuilder } from './activation/';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/extensibility/tenants/{tenantId}/extensions/{extensionId}/{contextType}/{contextId}
 */
export interface WithContextItemRequestBuilder extends BaseRequestBuilder<WithContextItemRequestBuilder> {
    /**
     * The activation property
     */
    get activation(): ActivationRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithContextItemRequestBuilderUriTemplate = "{+baseurl}/api/extensibility/tenants/{tenantId}/extensions/{extensionId}/{contextType}/{contextId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithContextItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithContextItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    activation: {
        requestsMetadata: ActivationRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
