/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { FilesRequestBuilderRequestsMetadata, type FilesRequestBuilder } from './files/index.js';
// @ts-ignore
import { ItemsRequestBuilderNavigationMetadata, ItemsRequestBuilderRequestsMetadata, type ItemsRequestBuilder } from './items/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/tenants/{tenantId}/marketplace
 */
export interface MarketplaceRequestBuilder extends BaseRequestBuilder<MarketplaceRequestBuilder> {
    /**
     * The files property
     */
    get files(): FilesRequestBuilder;
    /**
     * The items property
     */
    get items(): ItemsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const MarketplaceRequestBuilderUriTemplate = "{+baseurl}/api/tenants/{tenantId}/marketplace";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const MarketplaceRequestBuilderNavigationMetadata: Record<Exclude<keyof MarketplaceRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    files: {
        requestsMetadata: FilesRequestBuilderRequestsMetadata,
    },
    items: {
        requestsMetadata: ItemsRequestBuilderRequestsMetadata,
        navigationMetadata: ItemsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
