/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithItemItemRequestBuilder, WithItemItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/marketplace/tenants/{tenantId}/resources
 */
export interface ResourcesRequestBuilder extends BaseRequestBuilder<ResourcesRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.marketplace.tenants.item.resources.item collection
     * @param itemId Unique identifier of the item
     * @returns {WithItemItemRequestBuilder}
     */
     byItemId(itemId: string) : WithItemItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ResourcesRequestBuilderUriTemplate = "{+baseurl}/api/marketplace/tenants/{tenantId}/resources";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ResourcesRequestBuilderNavigationMetadata: Record<Exclude<keyof ResourcesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byItemId: {
        navigationMetadata: WithItemItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["itemId"],
    },
};
/* tslint:enable */
/* eslint-enable */
