/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { serializeMarketplaceItem, type MarketplaceItem } from '../../../../../models/index.js';
// @ts-ignore
import { type WithItemItemRequestBuilder, WithItemItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ResourcesPostResponse_items_validationErrors}
 */
// @ts-ignore
export function createResourcesPostResponse_items_validationErrorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoResourcesPostResponse_items_validationErrors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ResourcesPostResponse_items}
 */
// @ts-ignore
export function createResourcesPostResponse_itemsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoResourcesPostResponse_items;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ResourcesPostResponse}
 */
// @ts-ignore
export function createResourcesPostResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoResourcesPostResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoResourcesPostResponse(resourcesPostResponse: Partial<ResourcesPostResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "done": n => { resourcesPostResponse.done = n.getBooleanValue(); },
        "items": n => { resourcesPostResponse.items = n.getCollectionOfObjectValues<ResourcesPostResponse_items>(createResourcesPostResponse_itemsFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoResourcesPostResponse_items(resourcesPostResponse_items: Partial<ResourcesPostResponse_items> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "done": n => { resourcesPostResponse_items.done = n.getBooleanValue(); },
        "_id": n => { resourcesPostResponse_items.id = n.getStringValue(); },
        "inserted": n => { resourcesPostResponse_items.inserted = n.getBooleanValue(); },
        "itemId": n => { resourcesPostResponse_items.itemId = n.getStringValue(); },
        "name": n => { resourcesPostResponse_items.name = n.getStringValue(); },
        "updated": n => { resourcesPostResponse_items.updated = n.getBooleanValue(); },
        "validationErrors": n => { resourcesPostResponse_items.validationErrors = n.getCollectionOfObjectValues<ResourcesPostResponse_items_validationErrors>(createResourcesPostResponse_items_validationErrorsFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoResourcesPostResponse_items_validationErrors(resourcesPostResponse_items_validationErrors: Partial<ResourcesPostResponse_items_validationErrors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "field": n => { resourcesPostResponse_items_validationErrors.field = n.getStringValue(); },
        "message": n => { resourcesPostResponse_items_validationErrors.message = n.getStringValue(); },
    }
}
export interface ResourcesPostResponse extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The done property
     */
    done?: boolean | null;
    /**
     * The items property
     */
    items?: ResourcesPostResponse_items[] | null;
}
export interface ResourcesPostResponse_items extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The done property
     */
    done?: boolean | null;
    /**
     * The _id property
     */
    id?: string | null;
    /**
     * The inserted property
     */
    inserted?: boolean | null;
    /**
     * The itemId property
     */
    itemId?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The updated property
     */
    updated?: boolean | null;
    /**
     * The validationErrors property
     */
    validationErrors?: ResourcesPostResponse_items_validationErrors[] | null;
}
export interface ResourcesPostResponse_items_validationErrors extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The field property
     */
    field?: string | null;
    /**
     * The message property
     */
    message?: string | null;
}
/**
 * Builds and executes requests for operations under /api/marketplace/tenants/{tenantId}/resources
 */
export interface ResourcesRequestBuilder extends BaseRequestBuilder<ResourcesRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.marketplace.tenants.item.resources.item collection
     * @param itemId Unique identifier of the item
     * @returns {WithItemItemRequestBuilder}
     */
     byItemId(itemId: string) : WithItemItemRequestBuilder;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ResourcesPostResponse>}
     */
     post(body: MarketplaceItem, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ResourcesPostResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: MarketplaceItem, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeResourcesPostResponse(writer: SerializationWriter, resourcesPostResponse: Partial<ResourcesPostResponse> | undefined | null = {}) : void {
    if (resourcesPostResponse) {
        writer.writeBooleanValue("done", resourcesPostResponse.done);
        writer.writeCollectionOfObjectValues<ResourcesPostResponse_items>("items", resourcesPostResponse.items, serializeResourcesPostResponse_items);
        writer.writeAdditionalData(resourcesPostResponse.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeResourcesPostResponse_items(writer: SerializationWriter, resourcesPostResponse_items: Partial<ResourcesPostResponse_items> | undefined | null = {}) : void {
    if (resourcesPostResponse_items) {
        writer.writeBooleanValue("done", resourcesPostResponse_items.done);
        writer.writeStringValue("_id", resourcesPostResponse_items.id);
        writer.writeBooleanValue("inserted", resourcesPostResponse_items.inserted);
        writer.writeStringValue("itemId", resourcesPostResponse_items.itemId);
        writer.writeStringValue("name", resourcesPostResponse_items.name);
        writer.writeBooleanValue("updated", resourcesPostResponse_items.updated);
        writer.writeCollectionOfObjectValues<ResourcesPostResponse_items_validationErrors>("validationErrors", resourcesPostResponse_items.validationErrors, serializeResourcesPostResponse_items_validationErrors);
        writer.writeAdditionalData(resourcesPostResponse_items.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeResourcesPostResponse_items_validationErrors(writer: SerializationWriter, resourcesPostResponse_items_validationErrors: Partial<ResourcesPostResponse_items_validationErrors> | undefined | null = {}) : void {
    if (resourcesPostResponse_items_validationErrors) {
        writer.writeStringValue("field", resourcesPostResponse_items_validationErrors.field);
        writer.writeStringValue("message", resourcesPostResponse_items_validationErrors.message);
        writer.writeAdditionalData(resourcesPostResponse_items_validationErrors.additionalData);
    }
}
/**
 * Uri template for the request builder.
 */
export const ResourcesRequestBuilderUriTemplate = "{+baseurl}/api/marketplace/tenants/{tenantId}/resources";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ResourcesRequestBuilderNavigationMetadata: Record<Exclude<keyof ResourcesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byItemId: {
        navigationMetadata: WithItemItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["itemId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ResourcesRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ResourcesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createResourcesPostResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeMarketplaceItem,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
