/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { BulkRequestBuilderRequestsMetadata, type BulkRequestBuilder } from './bulk/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/extensibility/tenants/{tenantId}/extensions/{extensionId}/{contextType}/activation
 */
export interface ActivationRequestBuilder extends BaseRequestBuilder<ActivationRequestBuilder> {
    /**
     * The bulk property
     */
    get bulk(): BulkRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ActivationRequestBuilderUriTemplate = "{+baseurl}/api/extensibility/tenants/{tenantId}/extensions/{extensionId}/{contextType}/activation";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ActivationRequestBuilderNavigationMetadata: Record<Exclude<keyof ActivationRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    bulk: {
        requestsMetadata: BulkRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
