/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithTenantItemRequestBuilder, WithTenantItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/marketplace/tenants
 */
export interface TenantsRequestBuilder extends BaseRequestBuilder<TenantsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.marketplace.tenants.item collection
     * @param tenantId Unique identifier of the item
     * @returns {WithTenantItemRequestBuilder}
     */
     byTenantId(tenantId: string) : WithTenantItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const TenantsRequestBuilderUriTemplate = "{+baseurl}/api/marketplace/tenants";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const TenantsRequestBuilderNavigationMetadata: Record<Exclude<keyof TenantsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byTenantId: {
        navigationMetadata: WithTenantItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["tenantId"],
    },
};
/* tslint:enable */
/* eslint-enable */
