name: Publish

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: ${{ secrets.MIA_NPM_REGISTRY_URL }}
          scope: "mia-platform-internal"
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false
      - name: Build Monorepo
        run: pnpm i
        env:
          NODE_AUTH_TOKEN: ${{secrets.MIA_NPM_REGISTRY_TOKEN}}
      - run: pnpm build
      - name: Publish
        run: pnpm -r publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MIA_NPM_REGISTRY_TOKEN }}

