name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: ${{ secrets.MIA_NPM_REGISTRY_URL }}
          scope: "mia-platform-internal"
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false
      - name: Build Monorepo and Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MIA_NPM_REGISTRY_TOKEN }}
        run: |
          pnpm i --frozen-lockfile
          pnpm unit
          pnpm build
          pnpm -r publish --access restricted --registry ${{ secrets.MIA_NPM_REGISTRY_URL }}

