name: Publish

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
      - name: Build Monorepo and Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # We expect always tag in the form of `@owner/repo@version`. If it is not true,
          # this script will generate an invalid tag.
          tag=$(echo "${{ github.ref_name }}" | awk -F'[@/]' '{print "@"$2"/"$3}')
          # there is a post install that build every package in the workspace
          pnpm i --frozen-lockfile
          pnpm --filter=${tag} publish --access public --no-git-checks

