# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Release
on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Release Note
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          prerelease: ${{ startsWith(github.ref, 'refs/tags/') && contains(github.ref, '-rc.') }}
      
      - name: Publish Console SDK
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          pnpm i --frozen-lockfile
          pnpm sdk build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MIA_NPM_REGISTRY_TOKEN }}
      - name: Publish Vite Helpers
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          pnpm i --frozen-lockfile
          pnpm vh build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MIA_NPM_REGISTRY_TOKEN }}
      - name: Publish Webpack Helpers
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          pnpm i --frozen-lockfile
          pnpm wh build

      - run: pnpm -r publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MIA_NPM_REGISTRY_TOKEN }}