name: Test

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: "nexus.mia-platform.eu"
    # - name: Checks Secrets
    #   env:
    #     mia-internal-registry: ${{ secrets.MIA_NPM_INTERNAL_REGISTRY }}
    #     mia-internal-username: ${{ secrets.MIA_NPM_INTERNAL_USERNAME }}
    #     mia-internal-password: ${{ secrets.MIA_NPM_INTERNAL_PASSWORD }}
    #   if: |
    #     ${{ env.mia-internal-registry == '' || env.mia-internal-username == '' || env.mia-internal-password == ''}}
    #   run: |
    #     echo "some secrets has not been made"
    # - name: Login to Mia NPM Internal Registry
    #   run: |
    #     echo -e "@mia-platform-internal:registry=https://${{ secrets.MIA_NPM_INTERNAL_REGISTRY }}" > .npmrc
    #     echo -e "//${{ secrets.MIA_NPM_INTERNAL_REGISTRY }}:username=${{ secrets.MIA_NPM_INTERNAL_USERNAME }}" >> .npmrc
    #     echo -e "//${{ secrets.MIA_NPM_INTERNAL_REGISTRY }}:_password=${{ secrets.MIA_NPM_INTERNAL_PASSWORD }}" >> .npmrc
    - name: Install Packages
      run: npm ci; rm -f .npmrc
      env:
        NODE_AUTH_TOKEN: ${{ secrets.MIA_NPM_REGISTRY_TOKEN }}
    - run: npm run sdk build
    - run: npm run sdk test
    - run: npm run vite-helper build
    - run: npm run vite-helper test
    - run: npm run webpack-helper build
    - run: npm run webpack-helper test
    - name: Check License
      run: npm run check-license
    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
