name: Test

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: "https://nexus.mia-platform.eu/repository/npm-internal/"
        scope: "mia-platform-internal"
    - name: Install Packages
      run: npm ci; rm -f .npmrc
      env:
        NODE_AUTH_TOKEN: ${{secrets.MIA_NPM_REGISTRY_TOKEN}}
    - run: npm run sdk run build
    - run: npm run sdk test
    - run: npm run vite-helper run build
    - run: npm run vite-helper test
    - run: npm run webpack-helper run build
    - run: npm run webpack-helper test

    - uses: actions/checkout@v4
    - name: Use golang 1.20
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: install addlicense
      run: go install github.com/google/addlicense@latest
    - name: check license
      run: npm run check-license

    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
