# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Test

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: "https://nexus.mia-platform.eu/repository/npm-internal/"
        scope: "mia-platform-internal"
    - uses: pnpm/action-setup@v2
      name: Install pnpm
      with:
        version: 8
        run_install: false
    - name: Install Packages
      run: pnpm i; rm -f .npmrc
      env:
        NODE_AUTH_TOKEN: ${{secrets.MIA_NPM_REGISTRY_TOKEN}}
    - run: pnpm build
    - run: pnpm test
    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        flag-name: coverage for node:${{ matrix.node-version }}
        files: 'packages/*/coverage/clover.xml'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Go to check license
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'
    - name: Check license
      run: go install github.com/google/addlicense@latest
    - run: pnpm check-license

  publish:
    needs: ['test']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://nexus.mia-platform.eu/repository/npm-internal/"
          scope: "mia-platform-internal"
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false
      
      - name: Build Monorepo
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          pnpm i --frozen-lockfile
          pnpm build
      - name: Publish
        run: pnpm -r publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MIA_NPM_REGISTRY_TOKEN }}


