name: Test

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        run_install: false
    - name: Install Packages
      run: pnpm i
    - run: pnpm build
    - run: pnpm lint
    - run: pnpm test
    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        flag-name: coverage for node:${{ matrix.node-version }}
        files: 'packages/*/coverage/clover.xml'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel: true

    - name: Setup Go to check license
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'
    - name: Check license
      run: go install github.com/google/addlicense@latest
    - run: pnpm check-license
  post-tests:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Close coverage report
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
