# This workflow will do a clean install of node dependencies, build the source code and and then publish a package to npm when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Test and Publish

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  microfrontend-sdk-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Login to Mia NPM Internal  Registry
      run: |
        echo -e "@mia-platform-internal:registry=https://${{ secrets.MIA_NPM_INTERNAL_REGISTRY }}" > .npmrc
        echo -e "//${{ secrets.MIA_NPM_INTERNAL_REGISTRY }}:username=${{ secrets.MIA_NPM_INTERNAL_USERNAME }}" >> .npmrc
        echo -e "//${{ secrets.MIA_NPM_INTERNAL_REGISTRY }}:_password=${{ secrets.MIA_NPM_INTERNAL_PASSWORD }}" >> .npmrc
    - run: yarn
    - run: yarn sdk build
    - run: yarn sdk test
    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

  vite-helper-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn vite build
    - run: yarn vite test
    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

  webpack-helper-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn webpack-helper build
    - run: yarn webpack-helper test
    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

  check-license:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use golang 1.20
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: install addlicense
      run: go install github.com/google/addlicense@latest
    - name: check license
      run: npm run check-license

  publish-sdk-helper:
    runs-on: ubuntu-latest
    needs: [microfrontend-sdk-test]
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: ${{ secrets.MIA_NPM_REGISTRY_URL }}
      - run: yarn install --frozen-lockfile
      - run: yarn sdk build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MIA_NPM_REGISTRY_TOKEN }}

  publish-vite-helper:
    runs-on: ubuntu-latest
    needs: [vite-helper-test]
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: ${{ secrets.MIA_NPM_REGISTRY_URL }}
      - run: yarn install --frozen-lockfile
      - run: yarn webpack build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MIA_NPM_REGISTRY_TOKEN }}

  publish-webpack-helper:
    runs-on: ubuntu-latest
    needs: [webpack-helper-test]
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: ${{ secrets.MIA_NPM_REGISTRY_URL }}
      - run: yarn install --frozen-lockfile
      - run: yarn webpack build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MIA_NPM_REGISTRY_TOKEN }}