export enum EventsTypes {
  SET_SELECTED_PROJECT = 'SET_SELECTED_PROJECT',
  HIDE_ENVIRONMENT_SELECTION = 'HIDE_ENVIRONMENT_SELECTION',
  SHOW_ENVIRONMENT_SELECTION = 'SHOW_ENVIRONMENT_SELECTION',
  GET_CONFIG = 'GET_CONFIG', // Deprecated, probably used only from Visualize
  CHANGE_ENVIRONMENT_SELECTION = 'CHANGE_ENVIRONMENT_SELECTION',
  CHANGE_CONFIG_MAP_FILE = 'CHANGE_CONFIG_MAP_FILE',
  OVERWRITE_CONFIG_MAPS = 'OVERWRITE_CONFIG_MAPS',
  CREATE_SERVICE_ENVIRONMENT_VARIABLES = 'CREATE_SERVICE_ENVIRONMENT_VARIABLES',
  CHANGE_SERVICE_ENVIRONMENT_VARIABLES = 'CHANGE_SERVICE_ENVIRONMENT_VARIABLES',
  DELETE_ENDPOINT = 'DELETE_ENDPOINT',
  UPDATE_PROJECT_LINKS = 'UPDATE_PROJECT_LINKS',
  INVALIDATE_PROJECTS_CACHE = 'INVALIDATE_PROJECTS_CACHE',
  SEND_CONFIGURATION = 'SEND_CONFIGURATION',
  SET_DYNAMIC_ROUTES = 'SET_DYNAMIC_ROUTES'
}

export type Events = {
  action: EventsTypes,
  publisherId: string,
  payload: unknown,
}
